import streamlit as st
import os

from dotenv import load_dotenv
from openai import OpenAI

from rag.retrieve import retrieve_context

# =====================================
# OPENROUTER SETUP
# =====================================

load_dotenv()

api_key = os.getenv("OPENROUTER_API_KEY")

if not api_key:
    st.error("OPENROUTER_API_KEY not found in .env file")
    st.stop()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
)

# =====================================
# PAGE CONFIG
# =====================================

st.set_page_config(
    page_title="Naina AI",
    page_icon="👁️",
    layout="centered"
)

# =====================================
# UI
# =====================================

st.title("👁️ Naina AI")

st.subheader(
    "Eye Wellness & Visual Therapy Assistant"
)

question = st.text_input(
    "Ask a question"
)

# =====================================
# ASK BUTTON
# =====================================

if st.button("Ask"):

    if not question.strip():

        st.warning(
            "Please enter a question."
        )

    else:

        try:

            # Retrieve Context From PDFs
            with st.spinner(
                "Searching knowledge base..."
            ):

                context = retrieve_context(
                    question
                )

            prompt = f"""
You are Naina AI.

You are an Eye Wellness and Visual Therapy Assistant.

Rules:

1. Answer ONLY questions related to:
   - Eyes
   - Vision
   - Eye diseases
   - Eye wellness
   - Visual therapy
   - Amblyopia
   - Myopia
   - Hyperopia
   - Dry eyes
   - Eye strain
   - Binocular vision

2. Use the retrieved PDF context whenever relevant.

3. If the question is unrelated to eye health, respond:

"I am an Eye Wellness Assistant and can only answer eye-related questions."

4. Do not diagnose diseases.

5. Do not prescribe medications.

6. Keep answers simple and easy to understand.

Retrieved Context:

{context}

User Question:

{question}

Answer:
"""

            # =====================================
            # OPENROUTER RESPONSE
            # =====================================

            with st.spinner(
                "Generating answer..."
            ):

                response = client.chat.completions.create(
                    model="deepseek/deepseek-chat-v3",
                    messages=[
                        {
                            "role": "user",
                            "content": prompt
                        }
                    ]
                )

                answer = (
                    response
                    .choices[0]
                    .message
                    .content
                )

            st.success(
                "Answer generated by OpenRouter"
            )

            st.markdown(
                "## Answer"
            )

            st.write(
                answer
            )

        except Exception as e:

            st.error(
                f"Error: {e}"
            )

# =====================================
# FOOTER
# =====================================

st.divider()

with st.expander("About Naina AI"):

    st.write(
        """
        Naina AI is an Eye Wellness & Visual Therapy Assistant.

        It uses:

        • OpenRouter
        • DeepSeek Chat V3
        • Semantic Search (RAG)
        • ChromaDB Vector Store
        • Ophthalmology PDF Knowledge Base

        Responses are generated using
        retrieved information from eye-care documents.
        """
    )