import streamlit as st
import os
from dotenv import load_dotenv
import google.generativeai as genai
from rag.retrieve import retrieve_context

# GEMINI SETUP
load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    st.error("GEMINI_API_KEY not found in .env file")
    st.stop()

genai.configure(api_key=api_key)

model = genai.GenerativeModel(
    "models/gemini-2.5-flash"
)

# PAGE CONFIG
st.set_page_config(
    page_title="Naina AI",
    page_icon="👁️",
    layout="centered"
)

# UI
st.title("👁️ Naina AI")
st.subheader(
    "Eye Wellness & Visual Therapy Assistant"
)

question = st.text_input(
    "Ask a question"
)

# ASK BUTTON
if st.button("Ask"):

    if not question.strip():

        st.warning(
            "Please enter a question."
        )

    else:

        try:

            # Retrieve Context From PDFs
            with st.spinner(
                "Searching knowledge base..."
            ):

                context = retrieve_context(
                    question
                )

            # Prompt
            prompt = f"""
You are Naina AI.

You are an Eye Wellness and Visual Therapy Assistant.

Rules:

1. Answer ONLY questions related to:
   - Eyes
   - Vision
   - Eye diseases
   - Eye wellness
   - Visual therapy
   - Amblyopia
   - Myopia
   - Hyperopia
   - Dry eyes
   - Eye strain
   - Binocular vision

2. Use the retrieved PDF context whenever relevant.

3. If the question is unrelated to eye health, respond:

   "I am an Eye Wellness Assistant and can only answer eye-related questions."

4. Do not diagnose diseases.

5. Do not prescribe medications.

6. Keep answers simple and easy to understand.

Retrieved Context:

{context}

User Question:

{question}

Answer:
"""

            # Gemini Response

            with st.spinner(
                "Generating answer..."
            ):

                response = model.generate_content(
                    prompt
                )

            st.success(
                "Answer generated by Gemini"
            )

            st.markdown(
                "## Answer"
            )

            st.write(
                response.text
            )

        except Exception as e:

            error_text = str(e)

            if (
                "429" in error_text
                or "quota" in error_text.lower()
                or "ResourceExhausted" in error_text
            ):

                st.error(
                    "Gemini API quota exceeded. Please try again later."
                )

            else:

                st.error(
                    f"Actual Error: {e}"
                )

# FOOTER
st.divider()

with st.expander("About Naina AI"):

    st.write(
        """
        Naina AI is an Eye Wellness & Visual Therapy Assistant.

        It uses:

        • Gemini 2.5 Flash
        • Semantic Search (RAG)
        • ChromaDB Vector Store
        • Ophthalmology PDF Knowledge Base

        Responses are generated by Gemini using
        information retrieved from eye-care documents.
        """
    )